import { z } from 'zod';

/**
 * Kronus Agent Types
 *
 * Types and schemas for the Kronus knowledge oracle agent
 *
 * ## Summary Architecture - COMPLETE OVERVIEW
 *
 * There are FIVE distinct summary types in this system, all stored in Tartarus (web/lib/db):
 *
 * ### 1. Journal Entry Summary (`journal_entries.summary` / `JournalEntryIndex.summary`)
 * - **What**: 3-sentence AI-generated summary of a single commit/change
 * - **Purpose**: Kronus indexing - quick retrieval without reading full entry
 * - **Example**: "Upgraded AI SDK from 5.x to 6.0. Changed generateObject() to generateText().
 *   Affected 3 files in the AI modules."
 * - **Generated by**: AI when creating journal entry (mandatory field in AIOutputSchema)
 * - **Scope**: Single commit, specific code changes
 * - **DB Location**: MCP `data/journal.db` → `journal_entries.summary`
 *
 * ### 2. Journal Project Summary / Entry 0 (`project_summaries`)
 * - **What**: Living documentation of a SOFTWARE REPOSITORY
 * - **Purpose**: Full context about a codebase - architecture, tech stack, patterns
 * - **Fields**: summary, purpose, architecture, tech_stack, file_structure, patterns, etc.
 * - **Example**: "Developer Journal Workspace" repository documentation
 * - **Generated by**: Agent's raw_report processed by Kronus
 * - **Scope**: Entire codebase, evolves over time
 * - **Linked to Linear via**: `linear_project_id` or `linear_issue_id` fields
 * - **DB Location**: MCP `data/journal.db` → `project_summaries` (+ Tartarus mirror)
 *
 * ### 3. Document Summary (`documents.summary` / `DocumentIndex.summary`)
 * - **What**: AI-generated summary of writings, prompts, notes
 * - **Purpose**: Kronus indexing for repository documents
 * - **Example**: "System prompt for Kronus oracle mode. Defines personality, capabilities, response format."
 * - **Generated by**: AI via /api/ai/summarize endpoint
 * - **Scope**: Single document content
 * - **DB Location**: Tartarus `web/data/tartarus.db` → `documents.summary`
 *
 * ### 4. Linear Project Summary (`linear_projects.summary` / `LinearProjectIndex.summary`)
 * - **What**: AI-generated summary of Linear project description/content
 * - **Purpose**: Kronus indexing for task management context
 * - **Example**: "Sprint focused on AI integration. Targets Q1 release. 5 issues remaining."
 * - **Generated by**: AI during Linear sync (via /api/ai/summarize)
 * - **Scope**: Task management project (sprints, milestones)
 * - **DB Location**: Tartarus `web/data/tartarus.db` → `linear_projects.summary`
 *
 * ### 5. Linear Issue Summary (`linear_issues.summary` / `LinearIssueIndex.summary`)
 * - **What**: AI-generated summary of Linear issue description
 * - **Purpose**: Kronus indexing for individual tasks
 * - **Example**: "Bug fix for auth flow. User sessions expire too quickly. Priority: High."
 * - **Generated by**: AI during Linear sync (via /api/ai/summarize)
 * - **Scope**: Single task/ticket
 * - **DB Location**: Tartarus `web/data/tartarus.db` → `linear_issues.summary`
 *
 * ## Key Distinction: Linear Project ≠ Journal Project Summary (Entry 0)
 *
 * - **Linear Project**: Task management entity (sprints, milestones, work planning)
 *   Example: "AI Eval Sprint Q1" - tracks issues, progress, deadlines
 *
 * - **Journal Project Summary (Entry 0)**: Software repository documentation
 *   Example: "Developer Journal Workspace" - architecture, tech stack, patterns
 *
 * These can be LINKED via `linear_project_id` on ProjectSummary, but they are
 * fundamentally different entities serving different purposes:
 * - Linear Project = "What work are we doing?" (task management)
 * - Entry 0 = "What is this codebase?" (technical documentation)
 *
 * ## Summary Generation Endpoint
 *
 * All Tartarus summaries use: `POST /api/ai/summarize`
 * - Model: Haiku 4.5 (fast, cheap)
 * - Format: 3 sentences, dense information, no fluff
 */

/**
 * Input schema for kronus_ask tool
 */
export const KronusAskInputSchema = z.object({
  question: z.string().min(1).describe('Question about projects, work, or repository data'),
  repository: z.string().optional().describe('Focus on specific repository (optional)'),
  depth: z.enum(['quick', 'deep']).default('quick').describe('quick=summaries only, deep=full content access'),
});

export type KronusAskInput = z.infer<typeof KronusAskInputSchema>;

/**
 * Response from Kronus agent
 */
export interface KronusResponse {
  answer: string;
  sources: KronusSource[];
  depth_used: 'quick' | 'deep';
}

/**
 * Source reference in Kronus response
 */
export interface KronusSource {
  type: 'journal_entry' | 'project_summary' | 'document' | 'linear_issue' | 'linear_project' | 'attachment';
  identifier: string; // commit_hash, slug, ENG-XXX, etc.
  title?: string;
  relevance?: string; // Why this source was used
}

/**
 * Summaries index structure for quick mode
 */
export interface SummariesIndex {
  // Core journal data
  projectSummaries: ProjectSummaryIndex[];
  journalEntries: JournalEntryIndex[];

  // Linear integration
  linearIssues: LinearIssueIndex[];
  linearProjects: LinearProjectIndex[];

  // Repository content
  documents: DocumentIndex[];

  // Media & attachments
  attachments: AttachmentIndex[];
}

/**
 * Project Summary Index (Entry 0) - Software repository documentation
 *
 * This is the living documentation for a SOFTWARE REPOSITORY, not a Linear project.
 * Contains architecture, tech stack, patterns, file structure, etc.
 *
 * Can be optionally LINKED to a Linear project/issue via `linear_project_id` or `linear_issue_id`.
 */
export interface ProjectSummaryIndex {
  repository: string;
  summary: string | null;
  status: string | null;
  technologies: string | null;
  updated_at: string;
  entry_count?: number;
  // Linear integration - links this repo to task management
  linear_project_id?: string | null;
  linear_project_name?: string | null; // Resolved from Linear for display
  linear_issue_id?: string | null;
  linear_issue_identifier?: string | null; // Resolved from Linear for display (e.g., "ENG-123")
}

/**
 * Journal Entry Index - Single commit/change summary
 *
 * 3-sentence dense summary of a specific commit for Kronus indexing.
 * Not to be confused with Project Summary (Entry 0) which documents the entire repo.
 */
export interface JournalEntryIndex {
  commit_hash: string;
  repository: string;
  branch: string;
  date: string;
  summary: string | null; // 3-sentence AI-generated summary
  why?: string; // Include why for context
}

export interface LinearIssueIndex {
  identifier: string;
  title: string;
  summary: string | null;
  stateName: string | null;
  priority: number | null;
  projectName: string | null;
}

export interface LinearProjectIndex {
  id: string;
  name: string;
  summary: string | null;
  state: string | null;
  progress: number | null;
}

export interface DocumentIndex {
  slug: string;
  type: string;
  title: string;
  summary: string | null;
  language: string | null;
}

export interface AttachmentIndex {
  id: number;
  commit_hash: string;
  filename: string;
  mime_type: string;
  description: string | null;
}
